name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["dev"]
  # Trigger release on tag
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-rpi4:
    name: Build for Raspberry Pi 4 (aarch64)
    runs-on: ubuntu-latest
    env:
      OPENSSL_DIR: /usr/local/ssl
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y libssl-dev
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build (aarch64-unknown-linux-gnu)
        run: cross build --release --target aarch64-unknown-linux-gnu
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dyncf-pi4
          path: target/aarch64-unknown-linux-gnu/release/dyncf

  release:
    name: Release
    needs: build-rpi4
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dyncf-pi4
          path: ./release-assets
      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-assets/dyncf
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
